# -*- coding: utf-8 -*-
"""DL_PR1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1roltJTUx-b-tWQdC_YNnda21-iTdQZW5

# **TASK 1 — Data Loading, EDA & Preprocessing**

**Load Dataset**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import regularizers
from tensorflow.keras.callbacks import EarlyStopping

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

sns.set_style("whitegrid")

print("Libraries imported successfully")

"""**Load Dataset**"""

data = load_breast_cancer(as_frame=True)

X = data.data
y = data.target

print("X shape:", X.shape)
print("y shape:", y.shape)

"""**Check Target**"""

print(y.value_counts())

"""**See the Data**"""

X.head()

X.describe()

"""**Class Distribution Graph**"""

plt.figure(figsize=(6,4))

ax = sns.countplot(x=y)

plt.title("Target Class Distribution — Malignant (0) vs Benign (1)")
plt.xlabel("Target Class")
plt.ylabel("Count")

for container in ax.containers:
    ax.bar_label(container)

plt.show()

"""**Correlation Heatmap**"""

plt.figure(figsize=(15,12))

corr = X.corr()

sns.heatmap(
    corr,
    annot=False,
    cmap="coolwarm",
    linewidths=0.3
)

plt.title("Feature Correlation Heatmap")
plt.show()

"""**Train/Test Split**"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

"""**Scaling**"""

scaler = StandardScaler()

X_train_sc = scaler.fit_transform(X_train)
X_test_sc = scaler.transform(X_test)

print("Scaling completed")
print("Training data:", X_train_sc.shape)
print("Testing data:", X_test_sc.shape)

"""**Check Scaling**"""

print("Mean:")
print(X_train_sc.mean(axis=0).round(2))

print("\nStandard Deviation:")
print(X_train_sc.std(axis=0).round(2))

"""# **STEP 2 — Task 2: Single-Layer Perceptron (SLP)**

**Create the SLP model**
"""

slp_model = keras.Sequential([
    keras.layers.Dense(
        1,
        activation="sigmoid",
        input_shape=(30,)
    )
])

slp_model.summary()

"""**Compile the model**"""

slp_model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

print("SLP model compiled successfully")

"""**Train the SLP**"""

slp_history = slp_model.fit(
    X_train_sc,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

"""**Plot Loss**"""

plt.figure(figsize=(7,5))

plt.plot(
    slp_history.history["loss"],
    label="Training Loss",
    color="#CC0000"
)

plt.plot(
    slp_history.history["val_loss"],
    label="Validation Loss",
    color="#2C2C2C"
)

plt.title("SLP Training vs Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()

plt.show()

"""**Plot Accuracy**"""

plt.figure(figsize=(7,5))

plt.plot(
    slp_history.history["accuracy"],
    label="Training Accuracy",
    color="#CC0000"
)

plt.plot(
    slp_history.history["val_accuracy"],
    label="Validation Accuracy",
    color="#2C2C2C"
)

plt.title("SLP Training vs Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()

plt.show()

"""**Evaluate on Test Data**"""

slp_test_loss, slp_test_accuracy = slp_model.evaluate(
    X_test_sc,
    y_test,
    verbose=0
)

print("SLP Test Accuracy:", slp_test_accuracy)

"""**Classification Report**"""

slp_probabilities = slp_model.predict(X_test_sc, verbose=0)

slp_predictions = (slp_probabilities >= 0.5).astype(int).ravel()

print(classification_report(
    y_test,
    slp_predictions,
    target_names=["Malignant", "Benign"]
))

"""**Confusion Matrix**"""

slp_cm = confusion_matrix(
    y_test,
    slp_predictions
)

plt.figure(figsize=(6,5))

sns.heatmap(
    slp_cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=["Malignant", "Benign"],
    yticklabels=["Malignant", "Benign"]
)

plt.title("SLP Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

"""# **STEP 3 — Task 3: Multi-Layer Perceptron (MLP)**

**Create MLP with ReLU**
"""

mlp_relu = keras.Sequential([
    keras.layers.Dense(64, activation="relu", input_shape=(30,)),
    keras.layers.Dense(32, activation="relu"),
    keras.layers.Dense(1, activation="sigmoid")
])

mlp_relu.summary()

"""**Compile ReLU model**"""

mlp_relu.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

print("MLP ReLU model compiled successfully")

"""**Train ReLU model**"""

mlp_relu_history = mlp_relu.fit(
    X_train_sc,
    y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

"""**Check Test Accuracy**"""

mlp_relu_loss, mlp_relu_accuracy = mlp_relu.evaluate(
    X_test_sc,
    y_test,
    verbose=0
)

print("MLP ReLU Test Accuracy:", mlp_relu_accuracy)

"""**Create Tanh model**"""

mlp_tanh = keras.Sequential([
    keras.layers.Dense(64, activation="tanh", input_shape=(30,)),
    keras.layers.Dense(32, activation="tanh"),
    keras.layers.Dense(1, activation="sigmoid")
])

mlp_tanh.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

print("MLP Tanh model created")

"""**Train Tanh model**"""

mlp_tanh_history = mlp_tanh.fit(
    X_train_sc,
    y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

"""**Create Sigmoid hidden-layer model**"""

mlp_sigmoid = keras.Sequential([
    keras.layers.Dense(64, activation="sigmoid", input_shape=(30,)),
    keras.layers.Dense(32, activation="sigmoid"),
    keras.layers.Dense(1, activation="sigmoid")
])

mlp_sigmoid.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

print("MLP Sigmoid model created")

"""**Train Sigmoid model**"""

mlp_sigmoid_history = mlp_sigmoid.fit(
    X_train_sc,
    y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

"""**Compare the three activation functions**"""

plt.figure(figsize=(10, 6))

plt.plot(
    mlp_relu_history.history["val_accuracy"],
    label="ReLU"
)

plt.plot(
    mlp_tanh_history.history["val_accuracy"],
    label="Tanh"
)

plt.plot(
    mlp_sigmoid_history.history["val_accuracy"],
    label="Sigmoid"
)

plt.title("Validation Accuracy: ReLU vs Tanh vs Sigmoid")
plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy")
plt.legend()

plt.show()

"""**Get Test Accuracy of all three**"""

_, relu_acc = mlp_relu.evaluate(X_test_sc, y_test, verbose=0)
_, tanh_acc = mlp_tanh.evaluate(X_test_sc, y_test, verbose=0)
_, sigmoid_acc = mlp_sigmoid.evaluate(X_test_sc, y_test, verbose=0)

print("ReLU Test Accuracy:", relu_acc)
print("Tanh Test Accuracy:", tanh_acc)
print("Sigmoid Test Accuracy:", sigmoid_acc)

"""**Create comparison table**"""

activation_results = pd.DataFrame({
    "Activation Function": ["ReLU", "Tanh", "Sigmoid"],
    "Test Accuracy": [relu_acc, tanh_acc, sigmoid_acc]
})

activation_results

"""**Find the best activation**"""

best_activation = activation_results.loc[
    activation_results["Test Accuracy"].idxmax(),
    "Activation Function"
]

print("Best activation based on test accuracy:", best_activation)

"""# **STEP 4 — Task 4: Early Stopping & Overfitting**

**Create the MLP model**
"""

mlp_es = keras.Sequential([
    keras.layers.Dense(128, activation="relu", input_shape=(30,)),
    keras.layers.Dense(64, activation="relu"),
    keras.layers.Dense(1, activation="sigmoid")
])

mlp_es.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

mlp_es.summary()

"""**Create Early Stopping**"""

early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=15,
    restore_best_weights=True,
    verbose=1
)

print("Early Stopping created")

"""**Train with Early Stopping**"""

mlp_es_history = mlp_es.fit(
    X_train_sc,
    y_train,
    epochs=300,
    batch_size=32,
    validation_split=0.1,
    callbacks=[early_stopping],
    verbose=1
)

"""**Find the actual stopping epoch**"""

stopping_epoch = len(mlp_es_history.history["loss"])

print("Training stopped at epoch:", stopping_epoch)

"""**Plot Training vs Validation Loss**"""

plt.figure(figsize=(10, 6))

plt.plot(
    mlp_es_history.history["loss"],
    label="Training Loss"
)

plt.plot(
    mlp_es_history.history["val_loss"],
    label="Validation Loss"
)

plt.axvline(
    stopping_epoch - 1,
    color="red",
    linestyle="--",
    label=f"Stopping Epoch: {stopping_epoch}"
)

plt.title("MLP with Early Stopping - Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()

plt.show()

"""**Evaluate Early Stopping model**"""

es_loss, es_accuracy = mlp_es.evaluate(
    X_test_sc,
    y_test,
    verbose=0
)

print("MLP + Early Stopping Test Accuracy:", es_accuracy)

"""**Create model WITHOUT Early Stopping**"""

mlp_no_es = keras.Sequential([
    keras.layers.Dense(128, activation="relu", input_shape=(30,)),
    keras.layers.Dense(64, activation="relu"),
    keras.layers.Dense(1, activation="sigmoid")
])

mlp_no_es.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

print("Model without Early Stopping created")

"""**Train without Early Stopping**"""

mlp_no_es_history = mlp_no_es.fit(
    X_train_sc,
    y_train,
    epochs=300,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

"""**Compare Validation Loss**"""

plt.figure(figsize=(10, 6))

plt.plot(
    mlp_no_es_history.history["val_loss"],
    label="Without Early Stopping"
)

plt.plot(
    mlp_es_history.history["val_loss"],
    label="With Early Stopping"
)

plt.title("Validation Loss: With vs Without Early Stopping")
plt.xlabel("Epoch")
plt.ylabel("Validation Loss")
plt.legend()

plt.show()

"""**Evaluate model without Early Stopping**"""

no_es_loss, no_es_accuracy = mlp_no_es.evaluate(
    X_test_sc,
    y_test,
    verbose=0
)

print("MLP Without Early Stopping Test Accuracy:", no_es_accuracy)

"""**Compare the two models**"""

comparison = pd.DataFrame({
    "Model": [
        "MLP + Early Stopping",
        "MLP Without Early Stopping"
    ],
    "Test Accuracy": [
        es_accuracy,
        no_es_accuracy
    ]
})

comparison

"""# **STEP 5 — Task 5: Dropout Regularization**

**Create the Dropout model**
"""

dropout_model = keras.Sequential([
    keras.layers.Dense(128, activation="relu", input_shape=(30,)),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(64, activation="relu"),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(1, activation="sigmoid")
])

dropout_model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

dropout_model.summary()

"""**Create Early Stopping**"""

dropout_early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=20,
    restore_best_weights=True,
    verbose=1
)

print("Early Stopping created")

"""**Train Dropout 0.3 model**"""

dropout_history = dropout_model.fit(
    X_train_sc,
    y_train,
    epochs=300,
    batch_size=32,
    validation_split=0.1,
    callbacks=[dropout_early_stopping],
    verbose=1
)

"""**Evaluate Dropout 0.3**"""

dropout_loss, dropout_accuracy = dropout_model.evaluate(
    X_test_sc,
    y_test,
    verbose=0
)

print("Dropout 0.3 Test Accuracy:", dropout_accuracy)

"""**Compare different Dropout rates**"""

def create_dropout_model(rate):
    model = keras.Sequential([
        keras.layers.Dense(128, activation="relu", input_shape=(30,)),
        keras.layers.Dropout(rate),
        keras.layers.Dense(64, activation="relu"),
        keras.layers.Dropout(rate),
        keras.layers.Dense(1, activation="sigmoid")
    ])

    model.compile(
        optimizer="adam",
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )

    return model

"""**Train Dropout 0.1**"""

model_01 = create_dropout_model(0.1)

early_01 = EarlyStopping(
    monitor="val_loss",
    patience=20,
    restore_best_weights=True
)

history_01 = model_01.fit(
    X_train_sc,
    y_train,
    epochs=200,
    batch_size=32,
    validation_split=0.1,
    callbacks=[early_01],
    verbose=0
)

print("Dropout 0.1 training completed")

"""**Train Dropout 0.3**"""

model_03 = create_dropout_model(0.3)

early_03 = EarlyStopping(
    monitor="val_loss",
    patience=20,
    restore_best_weights=True
)

history_03 = model_03.fit(
    X_train_sc,
    y_train,
    epochs=200,
    batch_size=32,
    validation_split=0.1,
    callbacks=[early_03],
    verbose=0
)

print("Dropout 0.3 training completed")

"""**Train Dropout 0.5**"""

model_05 = create_dropout_model(0.5)

early_05 = EarlyStopping(
    monitor="val_loss",
    patience=20,
    restore_best_weights=True
)

history_05 = model_05.fit(
    X_train_sc,
    y_train,
    epochs=200,
    batch_size=32,
    validation_split=0.1,
    callbacks=[early_05],
    verbose=0
)

print("Dropout 0.5 training completed")

"""**Plot validation accuracy**"""

plt.figure(figsize=(10, 6))

plt.plot(
    history_01.history["val_accuracy"],
    label="Dropout 0.1"
)

plt.plot(
    history_03.history["val_accuracy"],
    label="Dropout 0.3"
)

plt.plot(
    history_05.history["val_accuracy"],
    label="Dropout 0.5"
)

plt.title("Validation Accuracy for Different Dropout Rates")
plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy")
plt.legend()

plt.show()

"""**Test Accuracy of all three**"""

_, acc_01 = model_01.evaluate(X_test_sc, y_test, verbose=0)
_, acc_03 = model_03.evaluate(X_test_sc, y_test, verbose=0)
_, acc_05 = model_05.evaluate(X_test_sc, y_test, verbose=0)

print("Dropout 0.1 Test Accuracy:", acc_01)
print("Dropout 0.3 Test Accuracy:", acc_03)
print("Dropout 0.5 Test Accuracy:", acc_05)

"""**Create comparison table**"""

dropout_results = pd.DataFrame({
    "Dropout Rate": [0.1, 0.3, 0.5],
    "Test Accuracy": [acc_01, acc_03, acc_05]
})

dropout_results

"""**Identify best dropout rate**"""

best_dropout_rate = dropout_results.loc[
    dropout_results["Test Accuracy"].idxmax(),
    "Dropout Rate"
]

print("Best Dropout Rate:", best_dropout_rate)

"""# **STEP 6 — Task 6: L1, L2 & L1-L2 Regularization**

**Create L2 model**
"""

l2_model = keras.Sequential([
    keras.layers.Dense(
        128,
        activation="relu",
        kernel_regularizer=regularizers.l2(0.001),
        input_shape=(30,)
    ),
    keras.layers.Dense(
        64,
        activation="relu",
        kernel_regularizer=regularizers.l2(0.001)
    ),
    keras.layers.Dense(1, activation="sigmoid")
])

l2_model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

l2_model.summary()

"""**Train L2 model**"""

l2_early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=20,
    restore_best_weights=True,
    verbose=1
)

l2_history = l2_model.fit(
    X_train_sc,
    y_train,
    epochs=300,
    batch_size=32,
    validation_split=0.1,
    callbacks=[l2_early_stopping],
    verbose=1
)

"""**Evaluate L2**"""

l2_loss, l2_accuracy = l2_model.evaluate(
    X_test_sc,
    y_test,
    verbose=0
)

print("L2 Test Accuracy:", l2_accuracy)

"""**Create L1 model**"""

l1_model = keras.Sequential([
    keras.layers.Dense(
        128,
        activation="relu",
        kernel_regularizer=regularizers.l1(0.001),
        input_shape=(30,)
    ),
    keras.layers.Dense(
        64,
        activation="relu",
        kernel_regularizer=regularizers.l1(0.001)
    ),
    keras.layers.Dense(1, activation="sigmoid")
])

l1_model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

l1_model.summary()

"""**Train L1 model**"""

l1_early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=20,
    restore_best_weights=True,
    verbose=1
)

l1_history = l1_model.fit(
    X_train_sc,
    y_train,
    epochs=300,
    batch_size=32,
    validation_split=0.1,
    callbacks=[l1_early_stopping],
    verbose=1
)

"""**Evaluate L1**"""

l1_loss, l1_accuracy = l1_model.evaluate(
    X_test_sc,
    y_test,
    verbose=0
)

print("L1 Test Accuracy:", l1_accuracy)

"""**Create L1-L2 model**"""

l1_l2_model = keras.Sequential([
    keras.layers.Dense(
        128,
        activation="relu",
        kernel_regularizer=regularizers.l1_l2(
            l1=0.0001,
            l2=0.001
        ),
        input_shape=(30,)
    ),
    keras.layers.Dense(
        64,
        activation="relu",
        kernel_regularizer=regularizers.l1_l2(
            l1=0.0001,
            l2=0.001
        )
    ),
    keras.layers.Dense(1, activation="sigmoid")
])

l1_l2_model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

l1_l2_model.summary()

"""**Train L1-L2 model**"""

l1_l2_early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=20,
    restore_best_weights=True,
    verbose=1
)

l1_l2_history = l1_l2_model.fit(
    X_train_sc,
    y_train,
    epochs=300,
    batch_size=32,
    validation_split=0.1,
    callbacks=[l1_l2_early_stopping],
    verbose=1
)

"""**Evaluate L1-L2**"""

l1_l2_loss, l1_l2_accuracy = l1_l2_model.evaluate(
    X_test_sc,
    y_test,
    verbose=0
)

print("L1-L2 Test Accuracy:", l1_l2_accuracy)

"""**Plot Training vs Validation Loss**"""

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

axes[0].plot(l1_history.history["loss"], label="Training Loss")
axes[0].plot(l1_history.history["val_loss"], label="Validation Loss")
axes[0].set_title("L1 Regularization")
axes[0].set_xlabel("Epoch")
axes[0].set_ylabel("Loss")
axes[0].legend()

axes[1].plot(l2_history.history["loss"], label="Training Loss")
axes[1].plot(l2_history.history["val_loss"], label="Validation Loss")
axes[1].set_title("L2 Regularization")
axes[1].set_xlabel("Epoch")
axes[1].set_ylabel("Loss")
axes[1].legend()

axes[2].plot(l1_l2_history.history["loss"], label="Training Loss")
axes[2].plot(l1_l2_history.history["val_loss"], label="Validation Loss")
axes[2].set_title("L1-L2 Regularization")
axes[2].set_xlabel("Epoch")
axes[2].set_ylabel("Loss")
axes[2].legend()

plt.tight_layout()
plt.show()

"""**Create a model without regularization**"""

no_reg_model = keras.Sequential([
    keras.layers.Dense(128, activation="relu", input_shape=(30,)),
    keras.layers.Dense(64, activation="relu"),
    keras.layers.Dense(1, activation="sigmoid")
])

no_reg_model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

no_reg_early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=20,
    restore_best_weights=True
)

no_reg_history = no_reg_model.fit(
    X_train_sc,
    y_train,
    epochs=300,
    batch_size=32,
    validation_split=0.1,
    callbacks=[no_reg_early_stopping],
    verbose=0
)

_, no_reg_accuracy = no_reg_model.evaluate(
    X_test_sc,
    y_test,
    verbose=0
)

print("No Regularization Test Accuracy:", no_reg_accuracy)

"""**Create accuracy comparison**"""

regularization_results = pd.DataFrame({
    "Model": [
        "No Regularization",
        "L1",
        "L2",
        "L1-L2"
    ],
    "Test Accuracy": [
        no_reg_accuracy,
        l1_accuracy,
        l2_accuracy,
        l1_l2_accuracy
    ]
})

regularization_results

"""**Create grouped bar chart**"""

plt.figure(figsize=(9, 6))

bars = plt.bar(
    regularization_results["Model"],
    regularization_results["Test Accuracy"],
    color=["#2C2C2C", "#CC0000", "#CC0000", "#CC0000"]
)

plt.title("Test Accuracy: Regularization Comparison")
plt.xlabel("Model")
plt.ylabel("Test Accuracy")
plt.ylim(0, 1)

for bar in bars:
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.01,
        f"{bar.get_height():.3f}",
        ha="center"
    )

plt.show()

"""# **STEP 7 — Final Model, Results & Clinical Insight**

**Create Final Model**
"""

final_model = keras.Sequential([
    keras.layers.Dense(
        128,
        activation="relu",
        kernel_regularizer=regularizers.l2(0.001),
        input_shape=(30,)
    ),

    keras.layers.Dropout(0.3),

    keras.layers.Dense(
        64,
        activation="relu",
        kernel_regularizer=regularizers.l2(0.001)
    ),

    keras.layers.Dropout(0.3),

    keras.layers.Dense(
        1,
        activation="sigmoid"
    )
])

final_model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

final_model.summary()

"""**Early Stopping**"""

final_early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=20,
    restore_best_weights=True,
    verbose=1
)

"""**Train Final Model**"""

final_history = final_model.fit(
    X_train_sc,
    y_train,
    epochs=300,
    batch_size=32,
    validation_split=0.1,
    callbacks=[final_early_stopping],
    verbose=1
)

"""**Plot Final Model Loss**"""

plt.figure(figsize=(9, 6))

plt.plot(
    final_history.history["loss"],
    label="Training Loss"
)

plt.plot(
    final_history.history["val_loss"],
    label="Validation Loss"
)

plt.title("Final Model Training vs Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()

plt.show()

"""**Plot Final Model Accuracy**"""

plt.figure(figsize=(9, 6))

plt.plot(
    final_history.history["accuracy"],
    label="Training Accuracy"
)

plt.plot(
    final_history.history["val_accuracy"],
    label="Validation Accuracy"
)

plt.title("Final Model Training vs Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()

plt.show()

"""**Evaluate Final Model**"""

final_loss, final_accuracy = final_model.evaluate(
    X_test_sc,
    y_test,
    verbose=0
)

print("Final Model Test Accuracy:", final_accuracy)

"""**Generate Predictions**"""

final_probabilities = final_model.predict(
    X_test_sc,
    verbose=0
)

final_predictions = (
    final_probabilities >= 0.5
).astype(int).ravel()

"""**Classification Report**"""

print(
    classification_report(
        y_test,
        final_predictions,
        target_names=["Malignant", "Benign"]
    )
)

"""**Confusion Matrix**"""

final_cm = confusion_matrix(
    y_test,
    final_predictions
)

plt.figure(figsize=(6, 5))

sns.heatmap(
    final_cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=["Malignant", "Benign"],
    yticklabels=["Malignant", "Benign"]
)

plt.title("Final Model Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

"""**Calculate Precision, Recall and F1**"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

final_precision = precision_score(
    y_test,
    final_predictions
)

final_recall = recall_score(
    y_test,
    final_predictions
)

final_f1 = f1_score(
    y_test,
    final_predictions
)

print("Accuracy :", final_accuracy)
print("Precision:", final_precision)
print("Recall   :", final_recall)
print("F1-Score :", final_f1)

"""**Create Final Results DataFrame**"""

results = pd.DataFrame([
    {
        "Model": "SLP",
        "Architecture": "30 → 1",
        "Regularization": "None",
        "Dropout Rate": 0,
        "Early Stopping": "No",
        "Test Accuracy": slp_test_accuracy,
        "Test Precision": precision_score(y_test, slp_predictions),
        "Test Recall": recall_score(y_test, slp_predictions),
        "Test F1-Score": f1_score(y_test, slp_predictions)
    },

    {
        "Model": "MLP-ReLU",
        "Architecture": "30 → 64 → 32 → 1",
        "Regularization": "None",
        "Dropout Rate": 0,
        "Early Stopping": "No",
        "Test Accuracy": relu_acc,
        "Test Precision": precision_score(
            y_test,
            (mlp_relu.predict(X_test_sc, verbose=0) >= 0.5).astype(int).ravel()
        ),
        "Test Recall": recall_score(
            y_test,
            (mlp_relu.predict(X_test_sc, verbose=0) >= 0.5).astype(int).ravel()
        ),
        "Test F1-Score": f1_score(
            y_test,
            (mlp_relu.predict(X_test_sc, verbose=0) >= 0.5).astype(int).ravel()
        )
    },

    {
        "Model": "MLP+ES",
        "Architecture": "30 → 128 → 64 → 1",
        "Regularization": "None",
        "Dropout Rate": 0,
        "Early Stopping": "Yes",
        "Test Accuracy": es_accuracy,
        "Test Precision": precision_score(
            y_test,
            (mlp_es.predict(X_test_sc, verbose=0) >= 0.5).astype(int).ravel()
        ),
        "Test Recall": recall_score(
            y_test,
            (mlp_es.predict(X_test_sc, verbose=0) >= 0.5).astype(int).ravel()
        ),
        "Test F1-Score": f1_score(
            y_test,
            (mlp_es.predict(X_test_sc, verbose=0) >= 0.5).astype(int).ravel()
        )
    },

    {
        "Model": "MLP+Dropout-best",
        "Architecture": "30 → 128 → 64 → 1",
        "Regularization": "Dropout",
        "Dropout Rate": best_dropout_rate,
        "Early Stopping": "Yes",
        "Test Accuracy": max(acc_01, acc_03, acc_05),
        "Test Precision": precision_score(
            y_test,
            (
                [
                    model_01,
                    model_03,
                    model_05
                ][
                    np.argmax([acc_01, acc_03, acc_05])
                ].predict(X_test_sc, verbose=0) >= 0.5
            ).astype(int).ravel()
        ),
        "Test Recall": recall_score(
            y_test,
            (
                [
                    model_01,
                    model_03,
                    model_05
                ][
                    np.argmax([acc_01, acc_03, acc_05])
                ].predict(X_test_sc, verbose=0) >= 0.5
            ).astype(int).ravel()
        ),
        "Test F1-Score": f1_score(
            y_test,
            (
                [
                    model_01,
                    model_03,
                    model_05
                ][
                    np.argmax([acc_01, acc_03, acc_05])
                ].predict(X_test_sc, verbose=0) >= 0.5
            ).astype(int).ravel()
        )
    },

    {
        "Model": "MLP+L2",
        "Architecture": "30 → 128 → 64 → 1",
        "Regularization": "L2",
        "Dropout Rate": 0,
        "Early Stopping": "Yes",
        "Test Accuracy": l2_accuracy,
        "Test Precision": precision_score(
            y_test,
            (l2_model.predict(X_test_sc, verbose=0) >= 0.5).astype(int).ravel()
        ),
        "Test Recall": recall_score(
            y_test,
            (l2_model.predict(X_test_sc, verbose=0) >= 0.5).astype(int).ravel()
        ),
        "Test F1-Score": f1_score(
            y_test,
            (l2_model.predict(X_test_sc, verbose=0) >= 0.5).astype(int).ravel()
        )
    },

    {
        "Model": "Final Combined Model",
        "Architecture": "30 → 128 → 64 → 1",
        "Regularization": "L2",
        "Dropout Rate": 0.3,
        "Early Stopping": "Yes",
        "Test Accuracy": final_accuracy,
        "Test Precision": final_precision,
        "Test Recall": final_recall,
        "Test F1-Score": final_f1
    }
])

results

"""**Highlight Best Results**"""

results.style.highlight_max(
    subset=[
        "Test Accuracy",
        "Test Precision",
        "Test Recall",
        "Test F1-Score"
    ],
    color="lightgreen"
)